### ISSUE TITLE
Make figma mock login page 

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#10]
**Task tets**

*Test 1*

1) Go to the blog works webpage, [Figma Design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=UAxS8YkJyfMlnNWX-0)
2) Click the present button located on the top-right corner of the webpage.
3) Hit the sign in button
4) If you already have an account then type in your information into the username and password
5) After you finished select Sign in
6) If this brings you to the homepage then this sign in was successful

*Test 2*

1) Go to the blog works webpage,[Figma Design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=UAxS8YkJyfMlnNWX-0)
2) Click the present button located on the top-right corner of the webpage.
3) Hit the sign in button
4) Type in all of your information to log in
5) Hit the box next to the words "Remember me"
6) Hit sign in
7) Once you are brought to the homepage, select the sign out button
8) Hit the sign in button
9) Your information should automatically be filled in
10) If the sign in button works then you know the remember me button works

**Comment by TwinkleLittleStarr** [comment]
- This task needs to be a dependency of a user story.

- This is also missing a Sprint 1 Label.

- This also needs some kind of test in the description. For Figma wireframes, you can at least direct people to the Figma page.

**Comment by TwinkleLittleStarr** [comment]
Still needs to be a dependency of a Figma User Story and the Figma Links are not public.

**Comment by TwinkleLittleStarr** [comment]
Tests 1 and 2 seem to fail, There is no homepage currently with this Figma link. Also remember this is just a wireframe so just "clicking x button" is sufficient since when testing, you can't fill in information in a text box.
