### ISSUE TITLE
As an investor, I would like to see the technologies documented, so that I can see how organized the development team is 

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#11]
Acceptance Test:

1. Click on Link https://github.com/cse442-at-ub/project_s23-group/tree/main
2. Verify Front end Documentation exists by clicking on "React Documentation.pdf"
3. Verifiy Backend Documentation exist by clicking on  "Backend Documentation.pdf"

**Comment by TwinkleLittleStarr** [comment]
If this is being worked on, possibly move it down the pipeline with the appropriate Tasks.

**Comment by TwinkleLittleStarr** [comment]
- Make sure this has some kind of _Acceptance Test_

**Comment by TwinkleLittleStarr** [comment]
The link should only link to main and not any other branch.
