### ISSUE TITLE
Figma mock for account creation

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#12]
Task tests

Test 1
1. Click this link [Figma Design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=l43bgRlQhLUEQTsM-0)
2. Click the present button located on the top-right corner of the webpage.
3. Click on sign up
4. Enter the necessary info. 
5. Click the sign up button.
6.  Should redirect user to home page signed in.

Test 2
1. Click this link [Figma Design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=l43bgRlQhLUEQTsM-0) 
2. Click the present button located on the top-right corner of the webpage.
3. Click sign in to be redirected to the sign in page.

**Comment by TwinkleLittleStarr** [comment]
- This task needs to be a dependency of a user story.

- This is also missing a Sprint 1 Label.

- This also needs some kind of test in the description. For Figma wireframes, you can at least direct people to the Figma page.

**Comment by TwinkleLittleStarr** [comment]
Still needs to be a dependency of a Figma User Story and the Figma Links are not public.

**Comment by TwinkleLittleStarr** [comment]
Same issue as the other tasks right now, the Figma links are inconsistent and should be all on one page to represent one application
