### ISSUE TITLE
Writing React Documentation

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#14]
**Task Test**:

1. Click on link: https://github.com/cse442-at-ub/project_s23-group/blob/documentation/ReactDocumentation.pdf
2. Check contents of documentation

**Comment by TwinkleLittleStarr** [comment]
- The format of the _Task Test_ needs to be corrected. The _Acceptance Tests_ title are only for User Stories. The instructions are good right now but need to be numbered like in the Style Guide (1. ... 2 .... 3. ...). 
- Make sure this has an Assignee as well.

**Comment by TwinkleLittleStarr** [comment]
Get rid of step 3. The link needs to be available by anyone who has access to the Zenhub since we can assume they have are involved with the project already.
