### ISSUE TITLE
Write SQL and PHP Documentation

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#15]
**Task Tests**

*Test 1*
1) Use the following link to access the file: [Link](https://github.com/cse442-at-ub/project_s23-group/blob/documentation/BackendDocumentation.pdf)
2) Check that the title says Backend Documentation Page

**Comment by TwinkleLittleStarr** [comment]
- This should not be blocking a User Story as this should be a dependency of a User Story and not the other way around. Only add dependencies on the User Stories and not Tasks.
- The format of the _Task Test_ needs to be corrected. The _acceptance tests_ title are only for User Stories. The instructions are good right now but need to be numbered like in the Style Guide (1. ... 2 .... 3. ...).

**Comment by TwinkleLittleStarr** [comment]
Add at least another step to the test so that someone can verify what they are and supposed to be seeing.
