### ISSUE TITLE
Make mockup feed page

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#16]
**Task Tests**

*Test 1*
1. Open the page for the Figma feed design using this link provided [Feed](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=ARaiRjMH9pjlgWvh-1)
2. Verify that all of the components are working and visible in the prototype in Figma

*Test 2*
1. Open the page for the Figma feed design using this link provided [Feed](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=ARaiRjMH9pjlgWvh-1)
2. Verify that the prototype on the home feed page navigates to different pages (Login, Signup, Profile) buttons when you start the prototype on the home feed page.
3. Make certain that the transition is smooth

**Comment by kangaroojae** [comment]
[HomeFeedLink](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?t=pleQmkzvWLEnR922-6)

**Comment by TwinkleLittleStarr** [comment]
Needs a test to be in the testing pipeline. Also needs a Figma User Story.
