### ISSUE TITLE
Make Figma UI for friend/followers's list

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#17]
**Task Test**:
1.  Open the link to access follower's list UI https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=ARaiRjMH9pjlgWvh-1
2. Press the present button located on the top-right side of the webpage
3. Then navigate to the profile page
4. Click on the follower's button to check for the bloggers' list of followers
5. Click on the outside of the follower's popup box to return to the profile page
6. Click on the following button to check for the list of people the blogger is following

**Comment by TwinkleLittleStarr** [comment]
This is linked to the wrong user story. This should not be connected to an actual future feature of the application. Connect and/ or make a separate User Story for Figma Wireframes.

**Comment by TwinkleLittleStarr** [comment]
There seems to be an issue with so many different Figma links. There should only be one Figma since there is only one application. Also this test is not sufficient since you need to show from the main application how to get here to the friend/followers' list.
