### ISSUE TITLE
Make a profile page mockup on figma

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#18]
**Task Test**

*Test 1*
1) Go to the blog works webpage, [Figma Design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=l43bgRlQhLUEQTsM-0)
2) Click the present button on the top-right corner of the webpage
3) Hit the sign in button
4) If you already have an account then type in your information into the username and password
5) After you finished select Sign in
6) This should bring you to the homepage. Select Profile at the top
7) If this brings you to a profile then you know it was successful

**Comment by TwinkleLittleStarr** [comment]
Needs a test to be in the testing pipeline. Also needs a Figma User Story instead of a future feature User Story.

**Comment by TwinkleLittleStarr** [comment]
This test does not seem to align with what is on the current link.
