### ISSUE TITLE
Make a Figma design for user timeline

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#19]
Task Testing

Test Case 1
1. Click this link [figma design](https://www.figma.com/file/v6DyhFDxJn7Q4Z0cCsTeJy/GYM_BLOG-HomePage?node-id=0%3A1&t=w6jzRS4Jb6IOyqKQ-0) then press play to go into the homepage.
2. Then click "Profile" to redirect to the timeline page.
3. Verify that the Timeline UI is complete.

**Comment by TwinkleLittleStarr** [comment]
- Follow the Style guide for correct testing format. Should not be **Task Testing** or **Test Case 1**.
- The Figma link seems to be outside of the application. Make sure this link is of the team Figma and not your own page. The whole Figma Wireframe should be able to flow from one frame to the next.

**Comment by TwinkleLittleStarr** [comment]
Tests 2 and 3 seem to be off as the link seems to direct to a separate static page. Also the Tests' formats need to align to the Style Guide, similar to the other tasks so far
