### ISSUE TITLE
As a blogger I would like to interact with a blog post, to be able to give feedback to the blogger.

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#2]
**Acceptance Test**

_Test 1_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the email being e@e.com and the password being 12345678
3. Click the first post
4. Write testComment in the comment box
5. Hit Post comment
6. Verify the comment is posted

_Test 2_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the email being e@e.com and the password being 12345678
3. Click the first post
4. Click the heart button to like the photo
5. Verify the total likes increase 
6. Verify the heart is a solid color
 

_Test 3_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the email being e@e.com and the password being 12345678
3. Click the first post
4. Click the share link button
5. Verify that the link was copied to your clipboard

**Comment by TwinkleLittleStarr** [comment]
Lacking acceptance tests.

**Comment by TwinkleLittleStarr** [comment]
These tests are too simple, they need examples of what to input in each field for an untrained user to properly test this.

**Comment by TwinkleLittleStarr** [comment]
Update this with separate tests for commenting, liking, and sharing as there is only just one big test for all of these.
