### ISSUE TITLE
Upload research files and Figma link txt file to Github

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#21]
**Task Tests:**

*Test 1*
1. Go to the [Github Repo](https://github.com/cse442-at-ub/project_s23-group/tree/main)
2. Verify that FigmaLink.txt, ReactDocumentation.pdf, and BackendDocumentation.pdf are there

**Comment by TwinkleLittleStarr** [comment]
- Make sure the test works, the GitHub seems to be missing all the documentation in step 2 currently.

- This is also missing an assignee.
