### ISSUE TITLE
Create a account login page 

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#22]
**Task Test**

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/ericTest/#
2. Click sign in at the top right of the screen
3. If this brings you to a page that says sign in you can verify theres a login page

**Comment by TwinkleLittleStarr** [comment]
Remember to add an assignee here!
You also don't need to reference the Figma in the Task Title.

**Comment by TwinkleLittleStarr** [comment]
Add a Sprint 3 label to this and reset the dependency to issue #8.
