### ISSUE TITLE
Create a Home page for the blog

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#23]
Task Test:

1. clone Github repository at https://github.com/cse442-at-ub/project_s23-group
2. open up command prompt
3. change directory into {dir_path}/workout-blog/workout-blog
4. run "npm install" command in terminal
5. run "npm start" command in terminal
6. A browser window will appear with the Home Page component rendered, Verify that the homepage is completed

**Comment by TwinkleLittleStarr** [comment]
Not necessary to include the Figma prototype in the title.
