### ISSUE TITLE
Create basic backend functionality for user creation and login

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#24]
**Task Tests:**

*Test 1*

1) Using postman, create a post request using form-data body to this directory: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/register.php
2) Post an "email", "name", and "password"
3) Login to [DB GUI](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin) using ub name and student number
4) Navigate to database cse442_2023_spring_team_w_db and table users
5) Check that the email, username, and password fields have been entered into database

*Test 2*

1) Using postman, create a post request using form-data body to this directory: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/login.php
2) Post an "email" and "password" from the [DB](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin) using ub name and student number
3) Confirm that a 200 (ok) status message is returned

*Test 3*

1) Using postman, create a post request using form-data body to this directory: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/login.php
2) Post an "email" and "password" that is not in the [DB](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin) using ub name and student number
3) Confirm that a 400 (error) status message is returned

**Comment by TwinkleLittleStarr** [comment]
Just add a Sprint 3 label to this since we technically did alter it during Sprint 3. This is to clear up confusion during grading.
