### ISSUE TITLE
As a blogger, I want to direct message users on Gym Blog so that I can ask questions about their diets and routines

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#27]
**Acceptance Tests**

*Test 1*
1. Click on: 1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Click the Messages button in the top right
4. Send a message to User: cbum@gmail.com Message: "Test"
5. Click the sign out button
6. Sign in with credentials 'username': cbum@gmail.com and 'password': password
7. Click the Messages button in the top right
8. Check to make sure that you have received message "Test" from John Smith

**Comment by TwinkleLittleStarr** [comment]
This user story is missing a Sprint 4 label.
