### ISSUE TITLE
As a blogger, I want to be able to add followers and see a list of followers, so that I can expand my network

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#28]
**Acceptance Tests:**

*Test 1*
1. Go to [Homepage](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#)
2. Click the login button
3. Sign in with credentials 'johnsmith@gmail.com' and 'password'
4. Click on Chris Bumstead's username that you see in the posting section
5. Click follow button in the top left section.
6. Click 'Gym Blog' and click 'Profile'
7. Verify that you can see users you are following by clicking the 'Following' button

*Test 2*
1. Go to [Homepage](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#)
2. Click the login button
3. Sign in with credentials 'cbum@gmail.com' and 'password'
4. Click the 'Profile' section
5. Click on the 'Follower' section
6. Verify that John Smith is added to your follower list
7. ![image](https://user-images.githubusercontent.com/78510734/232253157-d6d81a55-d937-4e26-825a-a73818a2334b.png)
8. Click on 'John Smith' and check out his profile page

**Comment by TwinkleLittleStarr** [comment]
Revise the title to replace _friends_ with _followers_.

**Comment by TwinkleLittleStarr** [comment]
Add Sprint 4 Label.
