### ISSUE TITLE
Create Sign up page

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#32]
Task Tests

Test 1

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#) and click sign up.
2. Click the top left arrow to redirect to the home page

Test 2

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#) and click sign up. Verify it looks like this:![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/4f90d6f1-1fb0-479c-b740-50e945f0699b)

2. Enter the following account information (change # to a random number if account is already taken):
Name: John Smith
Email: johnsmith(#)gmail.com
Password: password
Confirm Password: password
3. If the page is redirected to the home page, the register was successful.

Test 3

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#) and click sign up.
2. Click Sign in at the bottom to redirect to the login page

**Comment by TwinkleLittleStarr** [comment]
Should include a test with dummy information for a tester to sign up to our web app.

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials. Also, the verify that it looks like figma is not necessary in test 1.
