### ISSUE TITLE
Make how a post would look like on the feed page

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#34]
**Task tests**

1) Open the [Feed Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/) to go to a home webpage
2) Verify that there is an example post under the main image
3) Make sure that the user profile picture, username, title of the post, and preview Image are shown in the post

**Comment by TwinkleLittleStarr** [comment]
Add task tests.
