### ISSUE TITLE
As a blogger, I want the pages to be connected together so that when I click a link it brings me to another page

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#35]
**Acceptance Test**

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/ericTest/#
2. Click Sign in
3. Verify you were brought to the sign in page
4. Click Create an account
5. Verify you were brought to the sign up page
6. Click the back arrow in the top left
7. Verify you were brought to the homepage

**Comment by TwinkleLittleStarr** [comment]
Missing Acceptance tests.
