### ISSUE TITLE
Create a Profile page

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#36]
Task Tests

Test 1

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#) and click sign in.
2. Enter the credentials email:1 and password:1 it should redirect to the home page.
3. Click profile on the home page navbar.
![profile](https://user-images.githubusercontent.com/70614305/226116742-c1f058b2-7e8b-485b-b15d-f58bf303d2c4.png)
4. Verify that the profile page matches the Figma:
![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/05176a47-9d89-44b1-acb3-887cdbe46c4e)

**Comment by TwinkleLittleStarr** [comment]
Needs dependency.

**Comment by TwinkleLittleStarr** [comment]
The current link doesn't work and therefore the test fails.

**Comment by TwinkleLittleStarr** [comment]
The above test fails since when I click on the link, there is no profile button. If the button appears when you log in, add those directions to this test.
