### ISSUE TITLE
As a blog reader, I want to see the feed page, so I can see the content the bloggers have posted

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#37]
Acceptance Test:

Test 1

1.Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. See if content posted from other bloggers appears on the page
![image.png](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/daf83cf4-b140-490d-92b2-323080be0c2c)

**Comment by TwinkleLittleStarr** [comment]
Missing Acceptance tests.

**Comment by TwinkleLittleStarr** [comment]
Just add an image of the feed to this and this should be good
