### ISSUE TITLE
Create Coach Page

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#39]
Task Test

1. Navigate to the homepage: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/
2. Click on Coach Tab
3. View if coaches are displayed
4. View that their emails are displayed
5. Hover over the coach name and click
6. Verify if it brings you to their profile page

**Comment by TwinkleLittleStarr** [comment]
Due to only having just one task for this user story, it would be better if we just moved this task into a dependency of another. Change the title to "reuse", clear the labels and move this to the backlog.

**Comment by TwinkleLittleStarr** [comment]
Add a verification step for seeing if their email shows up on the page.
