### ISSUE TITLE
As a blogger, I want to be able to view posts that are favored by myself and others, so that I can review the most interesting posts.

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#4]
**Acceptance Tests**

*Test 1*
1) Click [here](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/)
2) Sign in with the credentials email: johnsmith@gmail.com password: password.
3) On the homepage, click the Top Posts button and ensure the posts are sorted by most likes

*Test 2*
1) On the homepage, click onto another user's profile, by clicking their profile picture next to their post
2) Follow the user, and Navigate back to the Hompage
3) While on the homepage, click the Following button and ensure the posts you see are only from people you are following

*Test 3*
1) While signed in, like a post,
2) Navigate to your own profile page
3) click favorites to see if posts you like shows up

**Comment by TwinkleLittleStarr** [comment]
This is an actual future feature so this should not have any dependencies yet, especially not a Figma Wireframe.

**Comment by TwinkleLittleStarr** [comment]
This should be moved out of the backlog pipeline since it's being worked on.

**Comment by TwinkleLittleStarr** [comment]
Add more robust user testing here.
