### ISSUE TITLE
Create test version of webpage hosted on web server

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#40]
**Task Test**

*Test 1*
1. Click on https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Inspect if website exist

**Comment by TwinkleLittleStarr** [comment]
Relink this task to a dependency of a different user story. Since it looks like this link would cover many different user stories, change it to #37 or #8.
