### ISSUE TITLE
Work on the functionality of login button 

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#43]
**Task Test**

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#
2. Click sign in at the top of the screen
3. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
4. Now click login 
5. This should redirect you to the homepage
6. If your on the homepage this was successful

**Comment by TwinkleLittleStarr** [comment]
The test currently fails when I enter the credentials above as it doesn't take me to the homepage.

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials.

**Comment by TwinkleLittleStarr** [comment]
Same thing as the other tasks, update the link above with the up to date main application.
