### ISSUE TITLE
Link the profile page to the rest of the pages

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#44]
**Task Test**

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#
2. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
3. Click profile on the top right
4. This should bring you to the profile
5. Click the home button in top left
6. This should bring you to the home page

**Comment by TwinkleLittleStarr** [comment]
Steps 4-5 fail, clicking on the homepage icon doesn't bring the user anywhere

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials.

**Comment by TwinkleLittleStarr** [comment]
Need to update the link used with the up to date web app link.
