### ISSUE TITLE
Add functionality to creating a post

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#45]
**Task Task**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/makePost/
2. Login with credentials 'username': johnsmith@gmail.com 'password': password
3. Click the Make Post button at the top
4. Use this photo for the post. ![dog.jpg](https://images.zenhubusercontent.com/63e3f673c771e13fa405c0c5/40d85641-0e54-4450-ad0e-548c463c92db)
5. Write the word "test" in the text box
6. Chose the progress tab from the dropdown
5. Click Post
7. Verify that you were redirected to the homepage
8. If you were not directed to the progress tab on the homepage select the progress
9. Verify that your photo is there with the words test below it
10. Check the other tabs and verify that the post was not shown there

**Comment by TwinkleLittleStarr** [comment]
Add a test image for the user to test the posting functionality with.
