### ISSUE TITLE
As a blogger, I want to be able to make a post, so that my post will appear on the feed page

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#46]
**Acceptance Task**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/
2. Click the Make Post button at the top
3. Use this photo for the post. ![dog.jpg](https://images.zenhubusercontent.com/63e3f673c771e13fa405c0c5/40d85641-0e54-4450-ad0e-548c463c92db)
4. Write the word "testTitle" in the title box
5. Write the word "testCap" in the caption box
6. Chose the progress tab from the dropdown
7. Click Post
8. Verify that you were redirected to the homepage
9. If you were not directed to the progress tab on the homepage select progress
10. Verify that your photo is there with the words testCap below it and testTitle above it
11. Check the other tabs and verify that the post was not shown there 
12. Verify that your post looks like the example image below
13. ![Screen Shot 2023-05-06 at 3.00.44 PM.png](https://images.zenhubusercontent.com/63e3f673c771e13fa405c0c5/ca1dda37-14b8-4447-abe0-83f838214e5c)

**Comment by TwinkleLittleStarr** [comment]
Doesn't seem to have any open tasks, move it into completed for this to be closed.

**Comment by TwinkleLittleStarr** [comment]
Step 4 is more ambiguous due to the fact we have two text boxes for title and description. Add more steps here.

**Comment by TwinkleLittleStarr** [comment]
Add image at last step to show how the user how the post should look like.
