### ISSUE TITLE
As a blogger, I want to be able to change the look of my profile page, so I can individualize my profile

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#48]
Acceptance Test:

Test 1

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/test2/#/
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. When signed in, click on profile
4. Click on settings in the navbar
![image](https://user-images.githubusercontent.com/70614305/232248676-c684754d-ff03-4614-b819-363839348e8d.png)
5. In settings write up a bio and select the 2 images below for profile picture and background respectively then press done.
![profilepic](https://user-images.githubusercontent.com/70614305/232248782-4c0088a6-7308-47c0-afef-18564a72fedd.jpg)
![run](https://user-images.githubusercontent.com/70614305/232248785-ce046c10-b7e9-46a9-94dd-6afbb2171e23.jpg)
6. View the change in bio, profile picture, and background image
![image](https://user-images.githubusercontent.com/70614305/232248717-8b952448-e599-4050-8acf-e05c753723c0.png)

**Comment by TwinkleLittleStarr** [comment]
Add Sprint 3 label. Also move this further into the pipeline as this is not a backlog issue. Lastly, add example images for someone to test with.
