### ISSUE TITLE
Create a settings page to allow users to change their bio and profile picture

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#49]
**Task Tests**

*Test 1*
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/# and sign in button on the top right.
2) Log in with the following credentials:
Email: johnsmith@gmail.com
Password: password
3) Click on the profile button on the top right:
![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/6ba27eba-2461-441d-bd46-fe08f7fba4a3)
4) Click on the settings button on the top left:
![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/e6f9ad88-b6ba-4b49-b1ca-15f6d6bb7369)
5) Enter a new bio, attach a new profile picture, and attach a new background image.
6) Click the done button.

**Comment by TwinkleLittleStarr** [comment]
The above test fails as it seems the picture are outdated as there is a settings button instead of a cog wheel currently.
