### ISSUE TITLE
As a blogger, I want to have a profile page that shows my timeline, so that I can see all my previous posts

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#5]
Acceptance Test:

Test 1

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials username: johnsmith@gmail.com password: password
2. Click on profile and check all components exist

![image.png](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/56ecfcbc-1719-4fe8-9ca7-8302135b06de)

**Comment by TwinkleLittleStarr** [comment]
Add Sprint 3 Label to this.

**Comment by TwinkleLittleStarr** [comment]
Add login credentials to this and change the picture to show what it is actually supposed to be shown instead of the mock user example.
