### ISSUE TITLE
Create the ability to view a single post

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#50]
**Task Tests**

*Test 1*
1) Click [here](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/)

2) Scroll down and click on the post

3) Ensure that you are redirected to a single post page ![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/afb623fd-fb76-47d5-a84a-391a4c3c518e)

**Comment by TwinkleLittleStarr** [comment]
Link needs to be updated as the test steps 2-3 fails currently.

**Comment by TwinkleLittleStarr** [comment]
Link needs to be updated as the test steps 2-3 fails currently.

**Comment by schaefe2** [comment]
Fixed
