### ISSUE TITLE
Create a mock follower and following lists in profile page

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#51]
**Task tests**

*Test 1*
1) Open up the [Blog](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/makePost/) 
2) Enter the credentials 'email': johnsmith@gmail.com and 'password': password it should redirect to the home page
3) Click on the Profile section
4) Verify that when you click 'Following' and 'Follower', you see a mock user list with a pop-up box.
5) Screen should show up like this
<img width="940" alt="image" src="https://user-images.githubusercontent.com/78510734/231253973-c910a6f6-af98-47dc-bfc1-e5491124dfd3.png">

**Comment by TwinkleLittleStarr** [comment]
Relink the user story to #28 since that would make more sense as a dependency for followers.

**Comment by TwinkleLittleStarr** [comment]
Change the login credentials of _1_ to a more accurate test user.

**Comment by TwinkleLittleStarr** [comment]
Set the user story to #28.

**Comment by TwinkleLittleStarr** [comment]
This is the wrong direction of user story to task dependency.
