### ISSUE TITLE
Create the follow feature to follow specific accounts

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#53]
**Task Test**

*Test 1*

1. Go to [Homepage](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#)
3. Click login with credentials 'username': johnsmith@gmail.com and 'password': password
5. Click on Chris' profile picture or username(bodybuilder with his back showing) under the posting section
6. Click follow button once and Navigate to your own profile page
7. Verify that 'following' counts have increased if you were not following that user already

*Test 2*
1. Go to [Homepage](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#)
2. Click login with credentials 'username': cbum@gmail.com and 'password': password
3. Click on John Smith's profile picture to go to its profile picture under the posting section
4. Click follow and log out
5. Again, log in with credentials 'username': johnsmith@gmail.com and 'password': password.
8. Go to the profile page and verify that the 'follower' count has gone up

*Test 3*

1. Go to [Homepage](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#)
2. Click login with credentials 'username': johnsmith@gmail.com and 'password': password
3. Go to the profile page
4. Click on the following button
5. Verify that users that you followed before show up as a list with profile pictures and usernames
6. Click on usernames or profile pictures and confirm that it redirects to their profile pages
7. Click 'Gym Blog' to redirect to the home page
9. Repeat steps 3 - 6 for the follower button

**Comment by TwinkleLittleStarr** [comment]
Break this task into two parts, one with the mock functionality from earlier Sprint 3, and one for the actual implementation of the follow functionality.

**Comment by TwinkleLittleStarr** [comment]
These tests fail as when I'm navigating the current link and follow the steps, I don't see the follow button anywhere.
