### ISSUE TITLE
Allow user to view other profiles

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#54]
Task Tests

Test 1

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/test2/#) and click sign in.
2. Enter the credentials email: johnsmith@gmail.com and password: password it should redirect to the home page.
3. Click on the profile picture of a post 
![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/fed8908f-4f75-473e-8fd3-c14f61464220)
4. Confirm it shows the account below 
![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/4903aca8-a7a5-419f-909b-e1c4388281aa)

**Comment by TwinkleLittleStarr** [comment]
Update the pictures used in this test as the website looks different than how its currently presented.
