### ISSUE TITLE
Add different section to the feedpage such as progress, dieting, and max

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#55]
**Task Test**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/ericTest/#/
2. Click sign in
3. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
4. Click sign in
5. Use this photo for the post. ![dog.jpg](https://images.zenhubusercontent.com/63e3f673c771e13fa405c0c5/40d85641-0e54-4450-ad0e-548c463c92db)
6. For the title and message write test34
7. For the tag select Diet
8. Hit Post
9. Click the drop down box and select Diet
10. Verify your post is there
11. Go to Progress and Max Weight and verify the post is not there

*Test 2*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/ericTest/#/
2. Click sign in
3. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
4. Click sign in
5. Use this photo for the post. ![dog.jpg](https://images.zenhubusercontent.com/63e3f673c771e13fa405c0c5/40d85641-0e54-4450-ad0e-548c463c92db)
6. For the title and message write test35
7. For the tag select Max Weight
8. Hit Post
9. Click the drop down box and select Max Weight
10. Verify your post is there
11. Go to Progress and Diet and verify the post is not there

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials.
