### ISSUE TITLE
Add the nav bar to the make a post page

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#56]
**Task Task**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/makePost/
2. Click the Sign In button on the top right
3. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
4. Click the Make Post button at the top
5. Verify there is a nav bar at the top
6. Click "Gym blog" and verify you were brought back to the homepage
7. Click Make a Post again, this time click profile and verify you were brought to the profile

**Comment by TwinkleLittleStarr** [comment]
The test looks good, just make sure to add credentials for someone login with at the beginning of this test.
