### ISSUE TITLE
Implement the share feature for posts

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#57]
**Task Tests**

*Test 1*
1) Click [here](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/)
2) Scroll down and click on a post
3) Ensure that you are redirected to a single post page ![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/afb623fd-fb76-47d5-a84a-391a4c3c518e)
4) Scroll down and click on the share button ![image.png](https://images.zenhubusercontent.com/63e42601feceb568bf711250/6c85837f-325b-4662-a325-964ac466bec8)
5) Open a new tab and press Ctrl+V
6) Press enter and ensure that you are directed to the same page

**Comment by TwinkleLittleStarr** [comment]
This is missing a dependency currently.
