### ISSUE TITLE
Upon clicking the username or profile picture of a user from the feedpage, you should be brought to that account

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#58]
**Task Test**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Click sign in and sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
3. Click on the profile picture of the first post
4. Verify you were brought to their account
5. Check the url to see what the profile ID is
6. Go back to the homepage
7. On the same post click their username
8. Verify you were brought to the same account
9. Go back to the homepage
10. Find a post with a different username than the one you chose earlier
11. Verify that you were brought to a different page than the previous post brought you to

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials.

**Comment by TwinkleLittleStarr** [comment]
I would like the above link to be the actual website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/. If I were to follow the steps on the actual website, the test would fail.
