### ISSUE TITLE
Make the users profile picture appear

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#59]
**Task Test**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/ericTest/#/ 
2. Click sign in
3. Sign in with the following credentials:
Email: johnsmith@gmail.com
Password: password
4. Click submit
5. If you scroll down you should now see the post
6. Verify that in the top left of the post there is a picture being displayed
7. Click that picture
8. Verify that the picture you clicked is the same as the picture on the profile

**Comment by TwinkleLittleStarr** [comment]
Needs appropriate login credentials.
