### ISSUE TITLE
Add update feature to posts

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#60]
Task Tests

Test 1

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Notice an edit button for your posts appears when signing in.
![image](https://user-images.githubusercontent.com/70614305/236641374-a609b50d-f33a-466e-9e79-9a31db21792b.png)
4. Click on edit button and change the title field to "title" then click on update to view changes.

Test 2

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Notice an edit button for your posts appears when signing in.
![image](https://user-images.githubusercontent.com/70614305/236641374-a609b50d-f33a-466e-9e79-9a31db21792b.png)
4. Click on edit button and upload the image below then click on update to view changes.
![pfworkout.jpg](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/759f3cf9-03bb-4b03-a202-48fb7560975a)

Test 3

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Notice an edit button for your posts appears when signing in.
![image](https://user-images.githubusercontent.com/70614305/236641374-a609b50d-f33a-466e-9e79-9a31db21792b.png)
4. Click on edit button and change the caption to "caption" then click on update to view changes.

**Comment by TwinkleLittleStarr** [comment]
Add dependency to user story #9.

**Comment by TwinkleLittleStarr** [comment]
Lacking task tests.

**Comment by TwinkleLittleStarr** [comment]
Change the images in the testing as they reflect the UI of the older website rather than the current one.
