### ISSUE TITLE
Implement like function for posts

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#62]
Task Tests:

Test 1 Testing the Feedpage: 
1. Login
2. Navigate to the landing page, and click the like button on a post.
3. Refresh the page and see if the like count is equivalent to the previous + 1
4. Check if this is also true for the same post on the user's timeline
5. Check if this is also true for the same post on its own page

Test 2 (Testing like function on the timeline page)
1. Navigate to a blogger's timeline and click on the like button on their blog post
2. Refresh the page to see if the like count is equivalent to the previous like count + 1
3. Check if this is also true for the same post on the feed page
4. Check if this is also true for the same post on its own page

Test 3(Testing the like function on the Singular Post page)
1. Click onto any blog post to redirect to a full-page post
2. Click the like button and refresh it to see the updated like count is equivalent to the previous + 1
3. Check if this is also true for the same post on the user's timeline
4. Check if this is also true for the same post on the feedpage

**Comment by TwinkleLittleStarr** [comment]
Make sure this has a user story as a dependency!
