### ISSUE TITLE
Add a tag that is shown on post

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#65]
**Task Test**

_Test 1_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the email being e@e.com and the password being 12345678
3. Look at the bottom right of the first post 
4. Verify that there is a tag there that either says "All", Progress","Diet","Top post", "Following or "Max Weight"
5. After clicking the progress tab, verify all post say progress
6. After clicking the diet tab, verify all post say diet
7. After clicking the max weight tab, verify all post say max weight
8. After clicking the all  tab, verify all post show up
9. After clicking the following tab, verify all post of users you follow appear
10. After clicking the top post tab, verify its sorted it most liked order

**Comment by TwinkleLittleStarr** [comment]
Add more concise verification that the label matches the filter above.

**Comment by TwinkleLittleStarr** [comment]
I think the only problem with this currently is that there should be more filter labels other than the current 3 we have right now since those were placeholders. Probably would need to change the testing words for the labels.

**Comment by TwinkleLittleStarr** [comment]
Once there is at least two separate filters for ("All", Progress","Diet"," "Max Weight") and ("Top post", "Following"). Update the testing to be more accurate about this.
