### ISSUE TITLE
Add delete feature to posts

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#66]
Task Test

Test 1

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Notice an edit button for your posts appears when signing in.
![image](https://user-images.githubusercontent.com/70614305/236641374-a609b50d-f33a-466e-9e79-9a31db21792b.png)
4. Click on the delete button to see the post is deleted.
5. Verify that the post is deleted on timeline and profile page
![image](https://user-images.githubusercontent.com/70614305/236639054-0062206c-f586-4441-b5a6-e41fd43a53bc.png)

**Comment by TwinkleLittleStarr** [comment]
Almost missed this problem, this task is a blocked by a user story instead of the other way around.

**Comment by TwinkleLittleStarr** [comment]
Since you added a picture of the edit button, there should be a similar picture shown of the delete button.
