### ISSUE TITLE
Update gym blog visuals

### ISSUE THREAD

**Issue by mkim52-bit** [cse442-at-ub/project_s23-group#68]
Task Tests

Test 1
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the credentials email: [johnsmith@gmail.com](mailto:johnsmith@gmail.com) password: password.
3. Click on the profile tab
4. Verify that Timeline is underlined then when clicking Favorites now that tab is underlined.
![image](https://user-images.githubusercontent.com/70614305/236647049-0a626c5b-1956-4220-bb49-624bd00c423e.png)
![image](https://user-images.githubusercontent.com/70614305/236647054-5fc57858-4cb3-4e22-b2bb-ff32050f38ce.png)

Test 2
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Verify that navigation options are underlined when hovered.

**Comment by TwinkleLittleStarr** [comment]
Change the user story is the example pictures more resemble  #4.
