### ISSUE TITLE
Add unfollow feature among users

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#69]
**Task tests**

*Test 1*
1) Open up the [Blog](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/) 
2) Enter the credentials 'email': johnsmith@gmail.com and 'password': password it should redirect to the home page
3) Click on any user's profile
4) Verify that follow button shows up on the top right of the screen
5) Click 'Follow' and check that button immediately turns to the 'Unfollow' option
6) Check that the profiles follower count has increased by 1

*Test 2*
1) Navigate to the home page
2) Click on 'Profile' on the navigation bar
3) On your profile page, ensure your following list has increased
4) Navigate to the profile page that you have just started following
5) Verify that the button stays as 'Unfollow' persistently
6) Click 'Unfollow' and return to your profile page
7) Check in your following list that you are no longer following that user anymore

**Comment by TwinkleLittleStarr** [comment]
Lacking testing and dependency.
