### ISSUE TITLE
Create a favorited section for user to see their favorited posts

### ISSUE THREAD

**Issue by sandershi34** [cse442-at-ub/project_s23-group#70]
Task Test 1:
1. navigate to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Like any post on the feed page
4. navigate to profile page
5. click on favorited 
6. check if the post you have liked previously shows up in the favorited section

**Comment by TwinkleLittleStarr** [comment]
Testing needs to be more robust with which posts exactly are the users supposed to see.
