### ISSUE TITLE
Create a filter to sort posts by liked and following

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#71]
**Task Tests**

*Test 1*
1) Click [here](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/)
2) Sign in with the credentials email: johnsmith@gmail.com password: password.
3) On the homepage, click the Top Posts button and ensure the posts are sorted by most likes
4) Now click on the Following button and ensure that only posts from followed accounts are being showed
5) Now click the All button and ensure that the most recent posts are being shown

**Comment by TwinkleLittleStarr** [comment]
Lacking testing and dependency

**Comment by TwinkleLittleStarr** [comment]
This test fails since there is no "Latest" filter.
