### ISSUE TITLE
Make the button that allows users to register as a coach

### ISSUE THREAD

**Issue by etomiello** [cse442-at-ub/project_s23-group#72]
**Task Test**

_Test 1_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#/
2. Click sign up
3. Verify that there is a box that you can check
4. Verify that next to the box it gives a warning that your email will be public
5. Click Sign up
6. After the redirect, hit the coaching tab
7. Verify that your account is listed

**Comment by TwinkleLittleStarr** [comment]
I think we need to show that this feature works other than just a "button," it would need more testing to show how the user would know this "coach button" functions correctly like verification on the logged in application.

**Comment by etomiello** [comment]
Update test so that multiple filters can be selected
