### ISSUE TITLE
As a new blogger, I want to create an account and be able to log in so I can start creating blog posts.

### ISSUE THREAD

**Issue by schaefe2** [cse442-at-ub/project_s23-group#8]
**Acceptance tests**

*Test1*

1. Go to [home page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev/#) and click "Sign Up".
image 
2. Verify that all the components exist

![image](https://user-images.githubusercontent.com/70614305/226129832-bc9729da-79aa-41e2-8da2-9c3b0440d127.png)

3. Enter the following information:
Name: John Smith
Email: johnsmith@gmail.com
password: Password123
confirm password: Password123

4. Click the "Sign Up" button below the fields

5. Click the "Sign In" button below

6. Sign in with the email and password from step 3.

**Comment by TwinkleLittleStarr** [comment]
Revise the title to include logging in as well.
