### ISSUE TITLE
As a blogger, I want to be able to edit my blog post, so I can make changes to my post

### ISSUE THREAD

**Issue by kangaroojae** [cse442-at-ub/project_s23-group#9]
Acceptance Test:

Test 1

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Click posts to create a new post using the image below, setting the title to "title", message to "message", and select Progress as the tag.
![matcha.jpg](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/8b07a9d7-0660-4ac7-a1c0-f9033d263914)
4. Notice an edit button for your posts appears when signing in.
![image.png](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/682ad583-cfcb-497b-a787-b2f279e37e51)
5. Click on edit button and change the title field to "hello" and click update to view changes.
6. Click on edit again to change the image this time using the image below and click update to view changes.
7. Click on edit again to change the caption, setting the new caption as "Caption" and click update to view changes.
8. Click on edit again to change the tag, setting the new tag to "Max Weight" and click update to view changes.
![pfworkout.jpg](https://images.zenhubusercontent.com/624b1b383fafc1e964d262f7/759f3cf9-03bb-4b03-a202-48fb7560975a)
9. Finally, click on edit and click on the delete button at the bottom.
10. Confirm the post was deleted. 

Test 2

1. Click on: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442w/dev
2. Sign in with the credentials email: johnsmith@gmail.com password: password.
3. Notice an edit button for your posts appears when signing in.
![image](https://user-images.githubusercontent.com/70614305/236641374-a609b50d-f33a-466e-9e79-9a31db21792b.png)
4. Click on the delete button to see the post is deleted.
5. Verify that the post is deleted on timeline and profile page
![image](https://user-images.githubusercontent.com/70614305/236639054-0062206c-f586-4441-b5a6-e41fd43a53bc.png)

**Comment by TwinkleLittleStarr** [comment]
There might be a slight typo in the title...

**Comment by TwinkleLittleStarr** [comment]
This user story is missing a Sprint 4 label.

**Comment by TwinkleLittleStarr** [comment]
Needs more robust testing... Have a test user create a post and then navigate to their post on the feed and then edit. You need to test for editing the title, image and description, with different combinations of those. Also add another test to delete posts.
